-- Explain plan
SET AUTOTRACE ON;
SET AUTOTRACE TRACEONLY;

--Tk prof
ALTER SESSION SET TIMED_STATISTICS=TRUE;
ALTER SESSION SET SQL_TRACE TRUE;

--Juntos
ALTER SESSION SET TIMED_STATISTICS=TRUE;
ALTER SESSION SET SQL_TRACE TRUE;
SET AUTOTRACE ON;