INSERT ALL
INTO departamento VALUES (1, 'Antioquia')
INTO departamento VALUES (2, 'Arauca')
INTO departamento VALUES (3, 'Atlantico')
INTO departamento VALUES (4, 'Bogota')
INTO departamento VALUES (5, 'Bolivar')
INTO departamento VALUES (6, 'Boyaca')
INTO departamento VALUES (7, 'Caldas')
INTO departamento VALUES (8, 'Cauca')
INTO departamento VALUES (9, 'Cundinamarca')
INTO departamento VALUES (10, 'Santander')
INTO departamento VALUES (11, 'Valle del Cauca')
SELECT * FROM dual;


INSERT ALL
INTO ciudad VALUES (1,'Medellin', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =1))
INTO ciudad VALUES (2,'Bello', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =1))
INTO ciudad VALUES (3,'Itagui', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =1))
INTO ciudad VALUES (4,'Sabaneta', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =1))
INTO ciudad VALUES (5,'Arauca', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =2))
INTO ciudad VALUES (6,'Arauquita', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =2))
INTO ciudad VALUES (7,'Barranquilla', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =3))
INTO ciudad VALUES (8,'Soledad', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =3))
INTO ciudad VALUES (9,'Puerto Colombia', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =3))
INTO ciudad VALUES (10,'Bogota', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =4))
INTO ciudad VALUES (11,'Cartagena', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =5))
INTO ciudad VALUES (12,'Mompos', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =5))
INTO ciudad VALUES (13,'Tunja', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =6))
INTO ciudad VALUES (14,'Sogamoso', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =6))
INTO ciudad VALUES (15,'Villa de Leyva', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =6))
INTO ciudad VALUES (16,'Manizales', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =7))
INTO ciudad VALUES (17,'La Dorada', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =7))
INTO ciudad VALUES (18,'Soacha', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =9))
INTO ciudad VALUES (19,'Chia', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =9))
INTO ciudad VALUES (20,'Girardot', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =9))
INTO ciudad VALUES (21,'Bucaramanga', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =10))
INTO ciudad VALUES (22,'Barrancabermeja', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =10))
INTO ciudad VALUES (23,'Cali', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =11))
INTO ciudad VALUES (24,'Tulua', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =11))
INTO ciudad VALUES (25,'Buenaventura', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =11))
INTO ciudad VALUES (26,'Yumbo', (SELECT REF(dep) FROM departamento dep WHERE dep.cod =11))
SELECT * FROM dual;