UPDATE empleado SET ventas = vent_varray(
) WHERE cc = 1;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),5)
) WHERE cc = 2;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),4)
) WHERE cc = 3;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),2)
) WHERE cc = 4;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),4)
) WHERE cc = 5;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),2)
) WHERE cc = 6;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),3)
) WHERE cc = 7;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),1)
) WHERE cc = 8;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),2)
) WHERE cc = 9;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),3)
) WHERE cc = 10;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),4)
) WHERE cc = 11;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),1)
) WHERE cc = 12;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),2)
) WHERE cc = 13;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),2)
) WHERE cc = 14;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),4)
) WHERE cc = 15;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),2)
) WHERE cc = 16;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),4)
) WHERE cc = 17;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),1)
) WHERE cc = 18;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),6)
) WHERE cc = 19;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),6)
) WHERE cc = 20;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),3)
) WHERE cc = 21;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),2)
) WHERE cc = 22;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),1)
) WHERE cc = 23;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),1)
) WHERE cc = 24;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),1)
) WHERE cc = 25;
UPDATE empleado SET ventas = vent_varray(
) WHERE cc = 26;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),1)
) WHERE cc = 27;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),3)
) WHERE cc = 28;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),2)
) WHERE cc = 29;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),4)
) WHERE cc = 30;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),2)
) WHERE cc = 31;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),2)
) WHERE cc = 32;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),4)
) WHERE cc = 33;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),6)
) WHERE cc = 34;
UPDATE empleado SET ventas = vent_varray(
) WHERE cc = 35;
UPDATE empleado SET ventas = vent_varray(
) WHERE cc = 36;
UPDATE empleado SET ventas = vent_varray(
) WHERE cc = 37;
UPDATE empleado SET ventas = vent_varray(
) WHERE cc = 38;
UPDATE empleado SET ventas = vent_varray(
) WHERE cc = 39;
UPDATE empleado SET ventas = vent_varray(
) WHERE cc = 40;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),2)
) WHERE cc = 41;
UPDATE empleado SET ventas = vent_varray(
) WHERE cc = 42;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),5)
) WHERE cc = 43;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),5)
) WHERE cc = 44;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),6)
) WHERE cc = 45;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),5)
) WHERE cc = 46;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),3)
) WHERE cc = 47;
UPDATE empleado SET ventas = vent_varray(
) WHERE cc = 48;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),4)
) WHERE cc = 49;
UPDATE empleado SET ventas = vent_varray(
) WHERE cc = 50;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),4)
) WHERE cc = 51;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),3)
) WHERE cc = 52;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),2)
) WHERE cc = 53;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),4)
) WHERE cc = 54;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),3)
) WHERE cc = 55;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),2)
) WHERE cc = 56;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),1)
) WHERE cc = 57;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),2)
) WHERE cc = 58;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),2)
) WHERE cc = 59;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),4)
) WHERE cc = 60;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),4)
) WHERE cc = 61;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),5)
) WHERE cc = 62;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =14),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),4)
) WHERE cc = 63;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =13),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),4)
) WHERE cc = 64;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),1)
) WHERE cc = 65;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =5),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =10),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =15),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),1)
) WHERE cc = 66;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),6),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =6),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =12),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),3),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =3),5),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =1),3)
) WHERE cc = 67;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =9),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =8),4),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =2),5)
) WHERE cc = 68;
UPDATE empleado SET ventas = vent_varray(
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =7),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),2),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =11),1),
venta_tipo((SELECT REF(pro) FROM producto pro WHERE pro.cod =4),4)
) WHERE cc = 69;